_target_: vit_up.eval_kits.probing_toolkit.dataset.cityscapes.CityscapesDataset
root: ${data_root}/cityscapes
split: "train"
transform: null 
target_transform: null 
include_labels: True
num_classes: 19  
tag: "cityscapes" 
