defaults:
  - /model/base/vit_up@_here_
  - _self_

# ckpt_path: ${mnt_dir}/logs/nf_dino/mjzwfd65/checkpoints/last.ckpt
ckpt_path: ${mnt_dir}/logs/nf_dino/uxpuzsn4/checkpoints/last.ckpt
out_size: null
name: vit_up