_target_: vit_up.eval_kits.upsamplers.backbones.base.PretrainedViTWrapper
# name: vit_small_patch14_dinov2.lvd142m
name: vit_small_plus_patch16_dinov3.lvd1689m
# name: vit_base_patch16_dinov3.lvd1689m
norm: True
